### ISSUE TITLE
how to reset/unset textures?

### ISSUE THREAD

**Issue by ergodicbreak** [dprojects/setTextures#1]
This may be a silly question, but how do you unset or reset a texture after it's applied? In other words how do you clear/remove a texture that was set?

edit: looking at the code, I guess entering an empty string for the filename works? However all the Texture properties are still on the geometry objects. It would be nice to be able to remove them completely.

**Comment by dprojects** [comment]
> This may be a silly question, but how do you unset or reset a texture after it's applied? In other words how do you clear/remove a texture that was set?

Yes, if you set empty string to URL the texture will be reset. If you reload the file the textures will not be visible.


> edit: looking at the code, I guess entering an empty string for the filename works? However all the Texture properties are still on the geometry objects. It would be nice to be able to remove them completely.

This should be new option in this case. But there is small problem with unload texture at current 3D view. I was trying to do that but the FreeCAD crashed. So for now you can only remove the URL and reload the FreeCAD project file.

Feel free to reopen this issue or create new one. I will think about it in the future, so maybe there will be some improvements.
